nodes:
  - name: local-dev
    address: 127.0.0.1
    default_runtime: docker-compose

instances:
  - name: dev-proxy
    role: proxy
    node: local-dev
    runtime: docker-compose
    paths:
      root: .kitsunebi/dev/dev-proxy
      live: .kitsunebi/dev/dev-proxy/data
    rcon:
      enabled: true
      host: 127.0.0.1
      port: 25575
      secret_ref: dev-proxy/rcon
    logs:
      journald_unit: kitsunebi-dev-proxy.service

  - name: dev-vanilla
    role: backend
    node: local-dev
    runtime: docker-compose
    paths:
      root: .kitsunebi/dev/dev-vanilla
      live: .kitsunebi/dev/dev-vanilla/data
    rcon:
      enabled: true
      host: 127.0.0.1
      port: 25576
      secret_ref: dev-vanilla/rcon
    logs:
      journald_unit: kitsunebi-dev-vanilla.service
