nodes:
  - name: kng01-game-01
    address: 10.10.30.20
    default_runtime: systemd-java

instances:
  - name: proxy-main-1
    role: proxy
    node: kng01-game-01
    runtime: systemd-java
    paths:
      root: /srv/kitsunebi/instances/proxy-main-1
      live: /srv/kitsunebi/instances/proxy-main-1/data
    rcon:
      enabled: true
      host: 127.0.0.1
      port: 25575
      secret_ref: proxy-main-1/rcon
    logs:
      journald_unit: kitsunebi@proxy-main-1.service

  - name: backend-vanilla-1
    role: backend
    node: kng01-game-01
    runtime: systemd-java
    paths:
      root: /srv/kitsunebi/instances/backend-vanilla-1
      live: /srv/kitsunebi/instances/backend-vanilla-1/data
    rcon:
      enabled: true
      host: 127.0.0.1
      port: 25576
      secret_ref: backend-vanilla-1/rcon
    logs:
      journald_unit: kitsunebi@backend-vanilla-1.service
